<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TeacherFullSeeder extends Seeder
{
    public function run(): void
    {
        $schoolId = 1;
        $now      = Carbon::now();

        // Subject ID map (from DB)
        // 1=English, 2=Hindi, 3=Sanskrit, 4=Mathematics, 5=EVS,
        // 6=Science, 7=Social Science, 8=Physics, 9=Chemistry,
        // 10=Biology, 11=History, 12=Geography, 13=Economics,
        // 14=Political Science, 15=Computer Science, 16=General Knowledge,
        // 17=Moral Science, 18=Drawing & Craft, 19=Physical Education

        $teachers = [

            // ─── NURSERY / LKG / UKG ────────────────────────────────────────
            [
                'employee_code'    => 'EMP105',
                'name'             => 'Mrs. Sunita Sharma',
                'email'            => 'sunita.sharma@redepublicschool.edu.in',
                'phone'            => '9876501101',
                'gender'           => 'female',
                'date_of_joining'  => '2015-06-01',
                'date_of_birth'    => '1985-03-12',
                'address'          => '12, Rose Garden Colony, Jaipur, Rajasthan - 302001',
                'qualification'    => 'B.Ed, Diploma in Early Childhood Education',
                'experience_years' => 11,
                'primary_subject'  => 'General Knowledge',
                'secondary_subject'=> 'Moral Science',
                'is_active'        => 1,
                'subjects'         => [16, 17, 18, 19],
                'educations'       => [
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Early Childhood Education',
                        'institution'        => 'University of Rajasthan',
                        'board_or_university'=> 'University of Rajasthan',
                        'passing_year'       => 2007,
                        'result'             => 'First Class',
                        'percentage'         => 74.50,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'B.A.',
                        'field_of_study'     => 'Education',
                        'institution'        => 'Maharani College, Jaipur',
                        'board_or_university'=> 'University of Rajasthan',
                        'passing_year'       => 2005,
                        'result'             => 'Second Class',
                        'percentage'         => 62.00,
                        'grade'              => 'B',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Bal Bharati Public School, Jaipur',
                        'designation'    => 'Pre-Primary Teacher',
                        'department'     => 'Pre-Primary',
                        'from_date'      => '2007-07-01',
                        'to_date'        => '2012-04-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Handled Nursery and LKG sections, conducted activity-based learning, parent-teacher meetings.',
                        'leaving_reason' => 'Better opportunity and higher pay scale',
                    ],
                    [
                        'organization'   => 'Delhi Public School, Jaipur',
                        'designation'    => 'Senior Pre-Primary Teacher',
                        'department'     => 'Pre-Primary',
                        'from_date'      => '2012-06-01',
                        'to_date'        => '2015-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Class teacher for UKG, coordinated annual day events, trained junior staff.',
                        'leaving_reason' => 'Relocated to current school',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP106',
                'name'             => 'Mrs. Rekha Devi',
                'email'            => 'rekha.devi@redepublicschool.edu.in',
                'phone'            => '9876501102',
                'gender'           => 'female',
                'date_of_joining'  => '2017-06-05',
                'date_of_birth'    => '1988-07-22',
                'address'          => '45, Shanti Nagar, Lucknow, Uttar Pradesh - 226001',
                'qualification'    => 'B.Ed, M.A. (Education)',
                'experience_years' => 9,
                'primary_subject'  => 'Moral Science',
                'secondary_subject'=> 'Drawing & Craft',
                'is_active'        => 1,
                'subjects'         => [17, 18, 16],
                'educations'       => [
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'Education',
                        'institution'        => 'Lucknow University',
                        'board_or_university'=> 'Lucknow University',
                        'passing_year'       => 2010,
                        'result'             => 'First Class',
                        'percentage'         => 71.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Primary Education',
                        'institution'        => 'Integral University, Lucknow',
                        'board_or_university'=> 'Integral University',
                        'passing_year'       => 2009,
                        'result'             => 'First Class',
                        'percentage'         => 68.50,
                        'grade'              => 'B+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'City Montessori School, Lucknow',
                        'designation'    => 'LKG Class Teacher',
                        'department'     => 'Pre-Primary',
                        'from_date'      => '2010-07-01',
                        'to_date'        => '2017-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Class teacher for LKG A & B, conducted art & craft sessions, organized inter-class competitions.',
                        'leaving_reason' => 'Family relocation',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP107',
                'name'             => 'Mrs. Anita Kumari',
                'email'            => 'anita.kumari@redepublicschool.edu.in',
                'phone'            => '9876501103',
                'gender'           => 'female',
                'date_of_joining'  => '2016-07-01',
                'date_of_birth'    => '1987-11-05',
                'address'          => '78, Gandhi Road, Patna, Bihar - 800001',
                'qualification'    => 'B.Ed, NTT (Nursery Teacher Training)',
                'experience_years' => 10,
                'primary_subject'  => 'General Knowledge',
                'secondary_subject'=> 'Moral Science',
                'is_active'        => 1,
                'subjects'         => [16, 17, 18],
                'educations'       => [
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Education',
                        'institution'        => 'Patna University',
                        'board_or_university'=> 'Patna University',
                        'passing_year'       => 2008,
                        'result'             => 'First Class',
                        'percentage'         => 73.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'NTT',
                        'field_of_study'     => 'Nursery Teacher Training',
                        'institution'        => 'NIIT Education, Patna',
                        'board_or_university'=> 'NIIT',
                        'passing_year'       => 2007,
                        'result'             => 'Distinction',
                        'percentage'         => 82.00,
                        'grade'              => 'A',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Kendriya Vidyalaya, Patna',
                        'designation'    => 'Pre-Primary Teacher',
                        'department'     => 'Pre-Primary',
                        'from_date'      => '2008-07-01',
                        'to_date'        => '2016-06-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught UKG and Nursery sections, developed activity-based curriculum, conducted parent orientation sessions.',
                        'leaving_reason' => 'Seeking better school environment',
                    ],
                ],
            ],

            // ─── CLASS 1–5 ──────────────────────────────────────────────────
            [
                'employee_code'    => 'EMP108',
                'name'             => 'Mr. Ramesh Kumar',
                'email'            => 'ramesh.kumar@redepublicschool.edu.in',
                'phone'            => '9876501104',
                'gender'           => 'male',
                'date_of_joining'  => '2013-06-10',
                'date_of_birth'    => '1982-04-18',
                'address'          => '23, MG Road, Bhopal, Madhya Pradesh - 462001',
                'qualification'    => 'M.A. (English), B.Ed',
                'experience_years' => 13,
                'primary_subject'  => 'English',
                'secondary_subject'=> 'Environmental Science',
                'is_active'        => 1,
                'subjects'         => [1, 5],
                'educations'       => [
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'English Literature',
                        'institution'        => 'Barkatullah University, Bhopal',
                        'board_or_university'=> 'Barkatullah University',
                        'passing_year'       => 2005,
                        'result'             => 'First Class',
                        'percentage'         => 72.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'English & Social Studies',
                        'institution'        => 'Regional Institute of Education, Bhopal',
                        'board_or_university'=> 'NCERT',
                        'passing_year'       => 2006,
                        'result'             => 'First Class',
                        'percentage'         => 78.00,
                        'grade'              => 'A',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Saraswati Shishu Mandir, Bhopal',
                        'designation'    => 'English Teacher',
                        'department'     => 'Primary',
                        'from_date'      => '2006-07-01',
                        'to_date'        => '2010-04-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught English for Class 1–5, prepared lesson plans, corrected assignments.',
                        'leaving_reason' => 'Promotion opportunity at another school',
                    ],
                    [
                        'organization'   => 'Vidyasagar Public School, Bhopal',
                        'designation'    => 'Senior English Teacher',
                        'department'     => 'Primary & Middle',
                        'from_date'      => '2010-06-01',
                        'to_date'        => '2013-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'English for Class 1–7, class teacher for Class 4, conducted elocution competitions.',
                        'leaving_reason' => 'Joined current school for better career growth',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP109',
                'name'             => 'Mrs. Geeta Singh',
                'email'            => 'geeta.singh@redepublicschool.edu.in',
                'phone'            => '9876501105',
                'gender'           => 'female',
                'date_of_joining'  => '2014-07-01',
                'date_of_birth'    => '1984-09-30',
                'address'          => '56, Nehru Colony, Varanasi, Uttar Pradesh - 221001',
                'qualification'    => 'M.Sc (Mathematics), B.Ed',
                'experience_years' => 12,
                'primary_subject'  => 'Mathematics',
                'secondary_subject'=> 'Computer Science',
                'is_active'        => 1,
                'subjects'         => [4, 15],
                'educations'       => [
                    [
                        'degree'             => 'M.Sc',
                        'field_of_study'     => 'Mathematics',
                        'institution'        => 'Banaras Hindu University',
                        'board_or_university'=> 'Banaras Hindu University',
                        'passing_year'       => 2006,
                        'result'             => 'First Class',
                        'percentage'         => 79.50,
                        'grade'              => 'A',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Mathematics & Science',
                        'institution'        => 'Banaras Hindu University',
                        'board_or_university'=> 'Banaras Hindu University',
                        'passing_year'       => 2007,
                        'result'             => 'First Class',
                        'percentage'         => 81.00,
                        'grade'              => 'A',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Holy Cross School, Varanasi',
                        'designation'    => 'Mathematics Teacher',
                        'department'     => 'Primary',
                        'from_date'      => '2007-07-01',
                        'to_date'        => '2014-06-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Maths for Class 1–6, introduced abacus-based learning, mentored weak students.',
                        'leaving_reason' => 'Better salary and growth prospects',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP110',
                'name'             => 'Mr. Suresh Verma',
                'email'            => 'suresh.verma@redepublicschool.edu.in',
                'phone'            => '9876501106',
                'gender'           => 'male',
                'date_of_joining'  => '2012-06-15',
                'date_of_birth'    => '1980-01-25',
                'address'          => '89, Tilak Nagar, Allahabad, Uttar Pradesh - 211001',
                'qualification'    => 'M.A. (Hindi), M.A. (Sanskrit), B.Ed',
                'experience_years' => 14,
                'primary_subject'  => 'Hindi',
                'secondary_subject'=> 'Sanskrit',
                'is_active'        => 1,
                'subjects'         => [2, 3],
                'educations'       => [
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'Hindi Literature',
                        'institution'        => 'Allahabad University',
                        'board_or_university'=> 'Allahabad University',
                        'passing_year'       => 2003,
                        'result'             => 'First Class',
                        'percentage'         => 76.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'Sanskrit',
                        'institution'        => 'Allahabad University',
                        'board_or_university'=> 'Allahabad University',
                        'passing_year'       => 2004,
                        'result'             => 'First Class',
                        'percentage'         => 69.00,
                        'grade'              => 'B',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Hindi & Sanskrit',
                        'institution'        => 'Regional Institute of Education, Allahabad',
                        'board_or_university'=> 'NCERT',
                        'passing_year'       => 2005,
                        'result'             => 'First Class',
                        'percentage'         => 74.00,
                        'grade'              => 'B+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Kendriya Vidyalaya, Allahabad',
                        'designation'    => 'Hindi & Sanskrit Teacher',
                        'department'     => 'Languages',
                        'from_date'      => '2005-07-01',
                        'to_date'        => '2012-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Hindi and Sanskrit for Class 1–8, organized language fests, prepared board exam students.',
                        'leaving_reason' => 'Sought private school environment',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP111',
                'name'             => 'Mrs. Lakshmi Iyer',
                'email'            => 'lakshmi.iyer@redepublicschool.edu.in',
                'phone'            => '9876501107',
                'gender'           => 'female',
                'date_of_joining'  => '2016-06-20',
                'date_of_birth'    => '1986-05-14',
                'address'          => '14, Anna Nagar, Chennai, Tamil Nadu - 600040',
                'qualification'    => 'M.Sc (Life Sciences), B.Ed',
                'experience_years' => 10,
                'primary_subject'  => 'Science',
                'secondary_subject'=> 'Environmental Science',
                'is_active'        => 1,
                'subjects'         => [6, 5, 10],
                'educations'       => [
                    [
                        'degree'             => 'M.Sc',
                        'field_of_study'     => 'Life Sciences',
                        'institution'        => 'University of Madras',
                        'board_or_university'=> 'University of Madras',
                        'passing_year'       => 2008,
                        'result'             => 'First Class with Distinction',
                        'percentage'         => 84.00,
                        'grade'              => 'A+',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Science & Biological Sciences',
                        'institution'        => 'Tamil Nadu Teachers Education University',
                        'board_or_university'=> 'TNTEU',
                        'passing_year'       => 2009,
                        'result'             => 'First Class',
                        'percentage'         => 77.50,
                        'grade'              => 'A',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'SBOA School, Chennai',
                        'designation'    => 'Science Teacher',
                        'department'     => 'Science',
                        'from_date'      => '2009-06-01',
                        'to_date'        => '2016-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Science and EVS for Class 3–7, conducted lab experiments, prepared students for science olympiads.',
                        'leaving_reason' => 'Spouse relocation',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP112',
                'name'             => 'Mrs. Asha Gupta',
                'email'            => 'asha.gupta@redepublicschool.edu.in',
                'phone'            => '9876501108',
                'gender'           => 'female',
                'date_of_joining'  => '2018-07-02',
                'date_of_birth'    => '1990-08-19',
                'address'          => '33, Shyam Nagar, Kanpur, Uttar Pradesh - 208001',
                'qualification'    => 'B.P.Ed, Diploma in Fine Arts',
                'experience_years' => 8,
                'primary_subject'  => 'Drawing & Craft',
                'secondary_subject'=> 'Physical Education',
                'is_active'        => 1,
                'subjects'         => [18, 19],
                'educations'       => [
                    [
                        'degree'             => 'B.P.Ed',
                        'field_of_study'     => 'Physical Education',
                        'institution'        => 'Lakshmibai National Institute of Physical Education, Gwalior',
                        'board_or_university'=> 'LNIPE',
                        'passing_year'       => 2012,
                        'result'             => 'First Class',
                        'percentage'         => 75.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'Diploma',
                        'field_of_study'     => 'Fine Arts & Craft',
                        'institution'        => 'Government College of Arts, Kanpur',
                        'board_or_university'=> 'CSJM University',
                        'passing_year'       => 2013,
                        'result'             => 'Distinction',
                        'percentage'         => 85.00,
                        'grade'              => 'A+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'St. Xavier School, Kanpur',
                        'designation'    => 'Art & PE Teacher',
                        'department'     => 'Co-curricular',
                        'from_date'      => '2013-07-01',
                        'to_date'        => '2018-06-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Conducted Drawing, Craft and Physical Education sessions for Class 1–8, organized sports day and art exhibitions.',
                        'leaving_reason' => 'Joined current school for better facilities',
                    ],
                ],
            ],

            // ─── CLASS 6–8 ──────────────────────────────────────────────────
            [
                'employee_code'    => 'EMP113',
                'name'             => 'Mr. Santosh Joshi',
                'email'            => 'santosh.joshi@redepublicschool.edu.in',
                'phone'            => '9876501109',
                'gender'           => 'male',
                'date_of_joining'  => '2011-06-01',
                'date_of_birth'    => '1979-12-03',
                'address'          => '67, Patel Nagar, Pune, Maharashtra - 411001',
                'qualification'    => 'M.Sc (Mathematics), M.C.A., B.Ed',
                'experience_years' => 15,
                'primary_subject'  => 'Mathematics',
                'secondary_subject'=> 'Computer Science',
                'is_active'        => 1,
                'subjects'         => [4, 15],
                'educations'       => [
                    [
                        'degree'             => 'M.Sc',
                        'field_of_study'     => 'Mathematics',
                        'institution'        => 'Savitribai Phule Pune University',
                        'board_or_university'=> 'SPPU',
                        'passing_year'       => 2002,
                        'result'             => 'First Class with Distinction',
                        'percentage'         => 86.00,
                        'grade'              => 'A+',
                    ],
                    [
                        'degree'             => 'M.C.A.',
                        'field_of_study'     => 'Computer Applications',
                        'institution'        => 'Symbiosis Institute, Pune',
                        'board_or_university'=> 'Symbiosis University',
                        'passing_year'       => 2004,
                        'result'             => 'First Class',
                        'percentage'         => 78.00,
                        'grade'              => 'A',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Mathematics & Computer Science',
                        'institution'        => 'SPPU, Pune',
                        'board_or_university'=> 'SPPU',
                        'passing_year'       => 2005,
                        'result'             => 'First Class',
                        'percentage'         => 80.00,
                        'grade'              => 'A',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Abhinav Vidyalay, Pune',
                        'designation'    => 'Mathematics Teacher',
                        'department'     => 'Mathematics',
                        'from_date'      => '2005-07-01',
                        'to_date'        => '2009-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Maths for Class 6–10, prepared students for Olympiad exams, designed worksheets.',
                        'leaving_reason' => 'Better pay scale',
                    ],
                    [
                        'organization'   => 'Maharashta English Medium School, Pune',
                        'designation'    => 'Senior Maths & Computer Teacher',
                        'department'     => 'Mathematics & IT',
                        'from_date'      => '2009-06-01',
                        'to_date'        => '2011-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Maths and Computer Science for Class 6–10, mentored students for board exams.',
                        'leaving_reason' => 'Relocated to current school',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP114',
                'name'             => 'Mrs. Nirmala Devi',
                'email'            => 'nirmala.devi@redepublicschool.edu.in',
                'phone'            => '9876501110',
                'gender'           => 'female',
                'date_of_joining'  => '2013-07-01',
                'date_of_birth'    => '1983-06-28',
                'address'          => '22, Ravi Nagar, Nagpur, Maharashtra - 440001',
                'qualification'    => 'M.Sc (Botany), B.Ed',
                'experience_years' => 13,
                'primary_subject'  => 'Science',
                'secondary_subject'=> 'Biology',
                'is_active'        => 1,
                'subjects'         => [6, 10],
                'educations'       => [
                    [
                        'degree'             => 'M.Sc',
                        'field_of_study'     => 'Botany',
                        'institution'        => 'Rashtrasant Tukadoji Maharaj Nagpur University',
                        'board_or_university'=> 'RTMNU',
                        'passing_year'       => 2005,
                        'result'             => 'First Class',
                        'percentage'         => 72.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Biology & General Science',
                        'institution'        => 'RTMNU, Nagpur',
                        'board_or_university'=> 'RTMNU',
                        'passing_year'       => 2006,
                        'result'             => 'First Class',
                        'percentage'         => 75.00,
                        'grade'              => 'B+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Somalwar High School, Nagpur',
                        'designation'    => 'Science Teacher',
                        'department'     => 'Science',
                        'from_date'      => '2006-06-01',
                        'to_date'        => '2013-06-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Science and Biology for Class 6–10, conducted practical sessions, prepared CBSE board students.',
                        'leaving_reason' => 'Joining school closer to home',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP115',
                'name'             => 'Mr. Harish Chandra',
                'email'            => 'harish.chandra@redepublicschool.edu.in',
                'phone'            => '9876501111',
                'gender'           => 'male',
                'date_of_joining'  => '2010-07-05',
                'date_of_birth'    => '1978-02-14',
                'address'          => '101, Civil Lines, Agra, Uttar Pradesh - 282001',
                'qualification'    => 'M.A. (History), M.A. (Geography), B.Ed',
                'experience_years' => 16,
                'primary_subject'  => 'Social Science',
                'secondary_subject'=> 'History',
                'is_active'        => 1,
                'subjects'         => [7, 11, 12],
                'educations'       => [
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'History',
                        'institution'        => 'Dr. Bhimrao Ambedkar University, Agra',
                        'board_or_university'=> 'DBRAU',
                        'passing_year'       => 2001,
                        'result'             => 'First Class',
                        'percentage'         => 68.00,
                        'grade'              => 'B',
                    ],
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'Geography',
                        'institution'        => 'Dr. Bhimrao Ambedkar University, Agra',
                        'board_or_university'=> 'DBRAU',
                        'passing_year'       => 2002,
                        'result'             => 'Second Class',
                        'percentage'         => 61.00,
                        'grade'              => 'B',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Social Studies',
                        'institution'        => 'Regional Institute of Education, Ajmer',
                        'board_or_university'=> 'NCERT',
                        'passing_year'       => 2003,
                        'result'             => 'First Class',
                        'percentage'         => 71.00,
                        'grade'              => 'B+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'St. Peter\'s College, Agra',
                        'designation'    => 'Social Studies Teacher',
                        'department'     => 'Humanities',
                        'from_date'      => '2003-07-01',
                        'to_date'        => '2010-06-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught History, Geography, Social Science for Class 6–10, organized heritage tours, prepared board students.',
                        'leaving_reason' => 'Seeking better institution with improved resources',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP116',
                'name'             => 'Mrs. Fatima Shaikh',
                'email'            => 'fatima.shaikh@redepublicschool.edu.in',
                'phone'            => '9876501112',
                'gender'           => 'female',
                'date_of_joining'  => '2015-07-01',
                'date_of_birth'    => '1985-10-08',
                'address'          => '55, Azad Nagar, Hyderabad, Telangana - 500001',
                'qualification'    => 'M.A. (English), M.A. (Sanskrit), B.Ed',
                'experience_years' => 11,
                'primary_subject'  => 'English',
                'secondary_subject'=> 'Sanskrit',
                'is_active'        => 1,
                'subjects'         => [1, 3],
                'educations'       => [
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'English Literature',
                        'institution'        => 'Osmania University, Hyderabad',
                        'board_or_university'=> 'Osmania University',
                        'passing_year'       => 2007,
                        'result'             => 'First Class',
                        'percentage'         => 76.50,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'Sanskrit',
                        'institution'        => 'Osmania University, Hyderabad',
                        'board_or_university'=> 'Osmania University',
                        'passing_year'       => 2008,
                        'result'             => 'First Class',
                        'percentage'         => 70.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'English & Sanskrit',
                        'institution'        => 'Telangana University',
                        'board_or_university'=> 'Telangana University',
                        'passing_year'       => 2009,
                        'result'             => 'First Class',
                        'percentage'         => 74.00,
                        'grade'              => 'B+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Little Flower High School, Hyderabad',
                        'designation'    => 'English & Sanskrit Teacher',
                        'department'     => 'Languages',
                        'from_date'      => '2009-06-01',
                        'to_date'        => '2015-06-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught English and Sanskrit for Class 6–9, conducted inter-school English debates, prepared CBSE board students.',
                        'leaving_reason' => 'Better career opportunity',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP117',
                'name'             => 'Mr. Dinesh Tiwari',
                'email'            => 'dinesh.tiwari@redepublicschool.edu.in',
                'phone'            => '9876501113',
                'gender'           => 'male',
                'date_of_joining'  => '2009-06-15',
                'date_of_birth'    => '1977-07-17',
                'address'          => '19, Ram Nagar, Gorakhpur, Uttar Pradesh - 273001',
                'qualification'    => 'M.A. (Hindi), B.Ed, NET Qualified',
                'experience_years' => 17,
                'primary_subject'  => 'Hindi',
                'secondary_subject'=> 'Moral Science',
                'is_active'        => 1,
                'subjects'         => [2, 17],
                'educations'       => [
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'Hindi',
                        'institution'        => 'Deen Dayal Upadhyay Gorakhpur University',
                        'board_or_university'=> 'DDU Gorakhpur University',
                        'passing_year'       => 2000,
                        'result'             => 'First Class',
                        'percentage'         => 73.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Hindi & Social Sciences',
                        'institution'        => 'DDU Gorakhpur University',
                        'board_or_university'=> 'DDU Gorakhpur University',
                        'passing_year'       => 2001,
                        'result'             => 'First Class',
                        'percentage'         => 70.00,
                        'grade'              => 'B+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Kendriya Vidyalaya, Gorakhpur',
                        'designation'    => 'Hindi Teacher',
                        'department'     => 'Languages',
                        'from_date'      => '2001-07-01',
                        'to_date'        => '2009-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Hindi for Class 6–10, coordinated school magazine, prepared Class 10 board students.',
                        'leaving_reason' => 'Opportunity in private sector with better pay',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP118',
                'name'             => 'Mr. Rajan Pillai',
                'email'            => 'rajan.pillai@redepublicschool.edu.in',
                'phone'            => '9876501114',
                'gender'           => 'male',
                'date_of_joining'  => '2017-07-10',
                'date_of_birth'    => '1989-03-25',
                'address'          => '7, Palarivattom, Kochi, Kerala - 682025',
                'qualification'    => 'M.P.Ed, Diploma in Yoga',
                'experience_years' => 9,
                'primary_subject'  => 'Physical Education',
                'secondary_subject'=> 'Drawing & Craft',
                'is_active'        => 1,
                'subjects'         => [19, 18],
                'educations'       => [
                    [
                        'degree'             => 'M.P.Ed',
                        'field_of_study'     => 'Physical Education',
                        'institution'        => 'Lakshmibai National College of Physical Education, Thiruvananthapuram',
                        'board_or_university'=> 'University of Kerala',
                        'passing_year'       => 2012,
                        'result'             => 'First Class',
                        'percentage'         => 78.00,
                        'grade'              => 'A',
                    ],
                    [
                        'degree'             => 'Diploma',
                        'field_of_study'     => 'Yoga & Meditation',
                        'institution'        => 'Sivananda Yoga Vedanta Centre, Thiruvananthapuram',
                        'board_or_university'=> 'Sivananda Yoga',
                        'passing_year'       => 2013,
                        'result'             => 'Distinction',
                        'percentage'         => 90.00,
                        'grade'              => 'A+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Bhavans Vidya Mandir, Kochi',
                        'designation'    => 'Physical Education Teacher',
                        'department'     => 'Sports & Co-curricular',
                        'from_date'      => '2013-06-01',
                        'to_date'        => '2017-06-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Conducted PE classes for Class 1–10, coached school cricket and football teams, organized annual sports meet.',
                        'leaving_reason' => 'Moved to current school for higher grade',
                    ],
                ],
            ],

            // ─── CLASS 9–10 ─────────────────────────────────────────────────
            [
                'employee_code'    => 'EMP119',
                'name'             => 'Mr. Ajay Sharma',
                'email'            => 'ajay.sharma@redepublicschool.edu.in',
                'phone'            => '9876501115',
                'gender'           => 'male',
                'date_of_joining'  => '2008-06-01',
                'date_of_birth'    => '1976-08-10',
                'address'          => '3, Vidhyadhar Nagar, Jaipur, Rajasthan - 302023',
                'qualification'    => 'M.Sc (Physics), B.Ed, NET Qualified',
                'experience_years' => 18,
                'primary_subject'  => 'Mathematics',
                'secondary_subject'=> 'Physics',
                'is_active'        => 1,
                'subjects'         => [4, 8],
                'educations'       => [
                    [
                        'degree'             => 'M.Sc',
                        'field_of_study'     => 'Physics',
                        'institution'        => 'University of Rajasthan',
                        'board_or_university'=> 'University of Rajasthan',
                        'passing_year'       => 1999,
                        'result'             => 'First Class with Distinction',
                        'percentage'         => 88.00,
                        'grade'              => 'A+',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Mathematics & Physical Sciences',
                        'institution'        => 'Regional Institute of Education, Ajmer',
                        'board_or_university'=> 'NCERT',
                        'passing_year'       => 2000,
                        'result'             => 'First Class',
                        'percentage'         => 82.00,
                        'grade'              => 'A',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Tagore International School, Jaipur',
                        'designation'    => 'Mathematics & Physics Teacher',
                        'department'     => 'Science & Mathematics',
                        'from_date'      => '2000-07-01',
                        'to_date'        => '2008-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Maths and Physics for Class 9–12, prepared students for JEE and board exams, conducted remedial classes.',
                        'leaving_reason' => 'Preferred teaching up to Class 10 for better work-life balance',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP120',
                'name'             => 'Mrs. Sonal Mehta',
                'email'            => 'sonal.mehta@redepublicschool.edu.in',
                'phone'            => '9876501116',
                'gender'           => 'female',
                'date_of_joining'  => '2012-07-01',
                'date_of_birth'    => '1982-01-20',
                'address'          => '88, Satellite Road, Ahmedabad, Gujarat - 380015',
                'qualification'    => 'M.Sc (Chemistry), B.Ed',
                'experience_years' => 14,
                'primary_subject'  => 'Chemistry',
                'secondary_subject'=> 'Biology',
                'is_active'        => 1,
                'subjects'         => [9, 10],
                'educations'       => [
                    [
                        'degree'             => 'M.Sc',
                        'field_of_study'     => 'Chemistry',
                        'institution'        => 'Gujarat University, Ahmedabad',
                        'board_or_university'=> 'Gujarat University',
                        'passing_year'       => 2004,
                        'result'             => 'First Class with Distinction',
                        'percentage'         => 85.50,
                        'grade'              => 'A+',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Chemistry & Biology',
                        'institution'        => 'Gujarat University',
                        'board_or_university'=> 'Gujarat University',
                        'passing_year'       => 2005,
                        'result'             => 'First Class',
                        'percentage'         => 79.00,
                        'grade'              => 'A',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Zydus School for Excellence, Ahmedabad',
                        'designation'    => 'Chemistry & Biology Teacher',
                        'department'     => 'Science',
                        'from_date'      => '2005-06-01',
                        'to_date'        => '2012-06-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Chemistry and Biology for Class 9–12, managed school science lab, guided students for NEET preparation.',
                        'leaving_reason' => 'Sought less stressful working environment',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP121',
                'name'             => 'Mr. Girish Kulkarni',
                'email'            => 'girish.kulkarni@redepublicschool.edu.in',
                'phone'            => '9876501117',
                'gender'           => 'male',
                'date_of_joining'  => '2014-06-16',
                'date_of_birth'    => '1981-04-07',
                'address'          => '44, Shivajinagar, Pune, Maharashtra - 411005',
                'qualification'    => 'M.A. (English), M.C.A., B.Ed',
                'experience_years' => 12,
                'primary_subject'  => 'English',
                'secondary_subject'=> 'Computer Science',
                'is_active'        => 1,
                'subjects'         => [1, 15],
                'educations'       => [
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'English Literature',
                        'institution'        => 'Fergusson College, Pune',
                        'board_or_university'=> 'SPPU',
                        'passing_year'       => 2003,
                        'result'             => 'First Class',
                        'percentage'         => 74.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'M.C.A.',
                        'field_of_study'     => 'Computer Applications',
                        'institution'        => 'SPPU, Pune',
                        'board_or_university'=> 'SPPU',
                        'passing_year'       => 2005,
                        'result'             => 'First Class',
                        'percentage'         => 77.00,
                        'grade'              => 'A',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'English & Computer Science',
                        'institution'        => 'SPPU, Pune',
                        'board_or_university'=> 'SPPU',
                        'passing_year'       => 2006,
                        'result'             => 'First Class',
                        'percentage'         => 76.00,
                        'grade'              => 'B+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Modern High School, Pune',
                        'designation'    => 'English & Computer Teacher',
                        'department'     => 'Languages & IT',
                        'from_date'      => '2006-06-01',
                        'to_date'        => '2014-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught English and Computer Science for Class 8–10, managed computer lab, trained students for essay and debate competitions.',
                        'leaving_reason' => 'Joined school with better infrastructure',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP122',
                'name'             => 'Mrs. Shobha Iyer',
                'email'            => 'shobha.iyer@redepublicschool.edu.in',
                'phone'            => '9876501118',
                'gender'           => 'female',
                'date_of_joining'  => '2010-06-01',
                'date_of_birth'    => '1980-09-15',
                'address'          => '9, T Nagar, Chennai, Tamil Nadu - 600017',
                'qualification'    => 'M.A. (Hindi), M.A. (Sanskrit), B.Ed',
                'experience_years' => 16,
                'primary_subject'  => 'Hindi',
                'secondary_subject'=> 'Sanskrit',
                'is_active'        => 1,
                'subjects'         => [2, 3],
                'educations'       => [
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'Hindi',
                        'institution'        => 'University of Madras',
                        'board_or_university'=> 'University of Madras',
                        'passing_year'       => 2002,
                        'result'             => 'First Class',
                        'percentage'         => 71.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'Sanskrit',
                        'institution'        => 'University of Madras',
                        'board_or_university'=> 'University of Madras',
                        'passing_year'       => 2003,
                        'result'             => 'First Class',
                        'percentage'         => 68.00,
                        'grade'              => 'B',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Hindi & Sanskrit',
                        'institution'        => 'Tamil Nadu Teachers Education University',
                        'board_or_university'=> 'TNTEU',
                        'passing_year'       => 2004,
                        'result'             => 'First Class',
                        'percentage'         => 72.00,
                        'grade'              => 'B+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'DAV School, Chennai',
                        'designation'    => 'Hindi & Sanskrit Teacher',
                        'department'     => 'Languages',
                        'from_date'      => '2004-06-01',
                        'to_date'        => '2010-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Hindi and Sanskrit for Class 6–10, organized Hindi Diwas celebrations, prepared board exam students.',
                        'leaving_reason' => 'Joined school closer to residence',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP123',
                'name'             => 'Mr. Sunil Tiwari',
                'email'            => 'sunil.tiwari@redepublicschool.edu.in',
                'phone'            => '9876501119',
                'gender'           => 'male',
                'date_of_joining'  => '2011-07-01',
                'date_of_birth'    => '1979-11-22',
                'address'          => '66, Hazratganj, Lucknow, Uttar Pradesh - 226001',
                'qualification'    => 'M.A. (Political Science), M.A. (Geography), B.Ed',
                'experience_years' => 15,
                'primary_subject'  => 'Social Science',
                'secondary_subject'=> 'Geography',
                'is_active'        => 1,
                'subjects'         => [7, 11, 12, 13, 14],
                'educations'       => [
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'Political Science',
                        'institution'        => 'Lucknow University',
                        'board_or_university'=> 'Lucknow University',
                        'passing_year'       => 2002,
                        'result'             => 'First Class',
                        'percentage'         => 70.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'M.A.',
                        'field_of_study'     => 'Geography',
                        'institution'        => 'Lucknow University',
                        'board_or_university'=> 'Lucknow University',
                        'passing_year'       => 2003,
                        'result'             => 'Second Class',
                        'percentage'         => 64.00,
                        'grade'              => 'B',
                    ],
                    [
                        'degree'             => 'B.Ed',
                        'field_of_study'     => 'Social Studies',
                        'institution'        => 'Lucknow University',
                        'board_or_university'=> 'Lucknow University',
                        'passing_year'       => 2004,
                        'result'             => 'First Class',
                        'percentage'         => 72.00,
                        'grade'              => 'B+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'La Martiniere College, Lucknow',
                        'designation'    => 'Social Studies Teacher',
                        'department'     => 'Humanities',
                        'from_date'      => '2004-07-01',
                        'to_date'        => '2011-06-30',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught Social Studies, History, Geography, Economics and Civics for Class 6–10, organized social awareness campaigns.',
                        'leaving_reason' => 'Career growth opportunity',
                    ],
                ],
            ],

            [
                'employee_code'    => 'EMP124',
                'name'             => 'Mr. Deepak Joshi',
                'email'            => 'deepak.joshi@redepublicschool.edu.in',
                'phone'            => '9876501120',
                'gender'           => 'male',
                'date_of_joining'  => '2019-06-10',
                'date_of_birth'    => '1992-06-30',
                'address'          => '21, Indira Nagar, Dehradun, Uttarakhand - 248001',
                'qualification'    => 'M.P.Ed, B.P.Ed',
                'experience_years' => 7,
                'primary_subject'  => 'Physical Education',
                'secondary_subject'=> 'General Knowledge',
                'is_active'        => 1,
                'subjects'         => [19, 16],
                'educations'       => [
                    [
                        'degree'             => 'M.P.Ed',
                        'field_of_study'     => 'Physical Education & Sports',
                        'institution'        => 'HNB Garhwal University, Srinagar',
                        'board_or_university'=> 'HNB Garhwal University',
                        'passing_year'       => 2015,
                        'result'             => 'First Class',
                        'percentage'         => 76.00,
                        'grade'              => 'B+',
                    ],
                    [
                        'degree'             => 'B.P.Ed',
                        'field_of_study'     => 'Physical Education',
                        'institution'        => 'HNB Garhwal University',
                        'board_or_university'=> 'HNB Garhwal University',
                        'passing_year'       => 2013,
                        'result'             => 'First Class',
                        'percentage'         => 74.00,
                        'grade'              => 'B+',
                    ],
                ],
                'experiences'      => [
                    [
                        'organization'   => 'Doon International School, Dehradun',
                        'designation'    => 'Physical Education Teacher',
                        'department'     => 'Sports',
                        'from_date'      => '2015-07-01',
                        'to_date'        => '2019-05-31',
                        'is_current'     => false,
                        'responsibilities'=> 'Taught PE for Class 6–12, coached school basketball and athletics teams, managed sports infrastructure.',
                        'leaving_reason' => 'Joined current school for career advancement',
                    ],
                ],
            ],
        ];

        foreach ($teachers as $data) {
            $subjectIds  = $data['subjects'];
            $educations  = $data['educations'];
            $experiences = $data['experiences'];

            unset($data['subjects'], $data['educations'], $data['experiences']);

            // Insert teacher
            $teacherId = DB::table('teachers')->insertGetId(array_merge($data, [
                'school_id'  => $schoolId,
                'created_at' => $now,
                'updated_at' => $now,
            ]));

            // Attach subjects
            $subjectRows = [];
            foreach ($subjectIds as $sid) {
                $subjectRows[] = [
                    'school_id'  => $schoolId,
                    'teacher_id' => $teacherId,
                    'subject_id' => $sid,
                ];
            }
            DB::table('teacher_subjects')->insert($subjectRows);

            // Insert educations
            foreach ($educations as $edu) {
                DB::table('teacher_educations')->insert(array_merge($edu, [
                    'teacher_id' => $teacherId,
                    'school_id'  => $schoolId,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]));
            }

            // Insert experiences
            foreach ($experiences as $exp) {
                DB::table('teacher_experiences')->insert(array_merge($exp, [
                    'teacher_id' => $teacherId,
                    'school_id'  => $schoolId,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]));
            }
        }

        $this->command->info('✅ 20 teachers seeded with full personal, education & experience details.');
    }
}
